# Generated by Django 2.2.5 on 2019-11-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=256, verbose_name='название_игры')),
                ('falls', models.IntegerField(default=0, verbose_name='Количество попыток')),
                ('number', models.IntegerField(verbose_name='Загаданное_число')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin_player', models.BooleanField(default=False, verbose_name='создатель_игры?')),
                ('player_name', models.CharField(max_length=256, verbose_name='имя_игрока')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='Игра')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player', verbose_name='Игрок')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='players', through='game.PlayerGameInfo', to='game.Player', verbose_name='Игроки'),
        ),
    ]
