# Generated by Django 2.2.5 on 2019-11-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='все игроки?'),
        ),
    ]
